### ISSUE TITLE
HTX does not build on standard RHEL 8

### ISSUE THREAD

**Issue by dougmill-ibm** [open-power/HTX#160]
As of RHEL 8.0, RedHat no longer provides the DAPL packages. It is not possible to build HTX on RHEL 8 without a hack. We need to have HTX stop using DAPL, or convert to whatever equivalent is available on newer Linux distros.

**Comment by avinashkuttan** [comment]
We can not remove hxedapl exerciser, since we have to test RDMA supported adapters.
Linux team suggests to use MOFED package for the dapl library installation.
MOFED package is available at following GSA location:
http://ausgsa.ibm.com/gsa/ausgsa/home/c/l/clsoto/public/MOFED_GA/ 

Installation steps are at following URL:
https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/Wb26014eb667b_4bb4_bb9b_29ea90c3ee19/page/MOFED%20RHEL%20Instructions

**Comment by avinashkuttan** [comment]
We can not remove hxedapl exerciser, since we have to test RDMA supported adapters.
Linux team suggests to use MOFED package for the dapl library installation.
Please install MOFED package and continue the HTX build.

**Comment by dougmill-ibm** [comment]
I don't think that installing MOFED is a practical solution. MOFED carries with it a lot of OS changes, and if our goal is to test a system that does not have MOFED then we deviate significantly from that test goal. If the tester is never going to need to run hxedapl, then we should be able to build an HTX without that.
Right now, there is no autoconf/configure mechanism, but at least there needs to be some sort of conf.h file or other mechanism by which one can disable the build of certain tests - for cases like this where there is a conflict.
Again, I don't view installing MOFED as a solution - it is much too disruptive in the cases where MOFED will not be tested.

**Comment by avinashkuttan** [comment]
The code change is approved and merged.
Closing this defect. 
pull request: https://github.com/open-power/HTX/pull/161
