### ISSUE TITLE
HTX fails to build, now requires libcxl.h

### ISSUE THREAD

**Issue by antonblanchard** [open-power/HTX#96]
HTX should not require the CAPI libraries to build.

**Comment by mehuljpatel** [comment]
hxecapi exer has been added recently (that uses memcopy AFU) and it requires libcxl.h for compilation.

Following pre-req/dependencies are captured in hxecapi.readme but I will add them to top level README.


Prerequisites:
--------------
1) Hardware should support CAIA Architecture, so this exerciser should run on Power 8 chip or above.

2) Libcxl library needs to be installed prior to running exerciser.
libcxl.so library needs to be placed under /usr/lib for Ubuntu
libcxl.so library needs to placed under /lib64/power8/ for RHEL7 LE

libcxl library can be installed using:
1. "apt-get install libcxl1" : After installing kindly see if libcxl.so is placed under /usr/lib.
    If not search where it is installed and move the file to /usr/lib. [Applied for Ubuntu only]
2. Download libcxl source from path "https://github.com/ibm-capi/libcxl" and compile and place the
    library file under /usr/lib if ubuntu or under /lib64/power8/ for RHEL7 LE

Dependent packages:
------------------
libcxl source is dependent package in order to compile hxecapi exerciser.
Kindly download source from "https://github.com/ibm-capi/libcxl" and place libcxl.h file under
directory /usr/include.

**Comment by mehuljpatel** [comment]
Added libcxl dependency info for building in top level README. Closing this issue.
